Added legacy validation checklists
dominodeorg/dominode-qgis-resources pull request #15
Opened 2020-10-02 07:08 UTC by Samweli

2020-10-02 09:45 UTC, ricardogsilva requested changes

2020-10-02 09:45 UTC, ricardogsilva commented on collections/dominode-resources/processing/legacy.py
> +        )
You are missing the definition of the algorithm's inputs, which is done by calling the algorithm's `self.addParameter()` method.

Check for example the code on `expressiontostringconverter.py` module (which is part of this repo)

2020-10-02 09:45 UTC, ricardogsilva commented on collections/dominode-resources/processing/legacy.py
> +class Legacy(QgsProcessingAlgorithm):
Please choose a more descriptive name that signals that this is a validation step. Something like `NoopValidator` or similar. Also, please change the name of the file to reflect that, to be consistent with how the other algorithm files that exist on this repo are being named.

2020-10-02 09:45 UTC, ricardogsilva commented on collections/dominode-resources/processing/legacy.py
> +        return self.tr('Legacy')
Please be a bit more verbose on these names to specify clearly what this is (similar to the request for changing the class name above)

2020-10-02 09:45 UTC, ricardogsilva commented on collections/dominode-resources/checklists/legacy-vector.json
> +        "output_name": "Result"
This should be the name you used to define your algorithm's output (check line 14 of the `processing/legacy.py` file below)

2020-10-02 09:45 UTC, ricardogsilva commented on collections/dominode-resources/checklists/legacy-raster.json
> +        "output_name": "Result"
This should be the name you used to define your algorithm's output (check line 14 of the `processing/legacy.py` file below)

2020-10-06 10:45 UTC, ricardogsilva requested changes
Please fix the errors on the automation

2020-10-06 10:45 UTC, ricardogsilva commented on collections/dominode-resources/checklists/legacy-raster.json
> +        "algorithm_id": "script:legacy",
You need to update this to reflect the new name, which seems to be `script:noopvalidator` (please test it out)

2020-10-06 10:45 UTC, ricardogsilva commented on collections/dominode-resources/checklists/legacy-vector.json
> +        "algorithm_id": "script:legacy",
You need to update this to reflect the new name, which seems to be `script:noopvalidator` (please test it out)

2020-10-06 10:50 UTC, ricardogsilva commented
@Samweli 

Some additional comment:

- Please remember remove the `draft` status when you think the work is ready to be merged
- In addition, please explicitly request a review by using the github reviews feature. Otherwise I may miss it :wink: 
- Finally, please provide a brief description for the PR to state what is included, including a reference to the issue that it relates to. If the PR fixes the issue (and in this case it does) please use the appropriate github reference, e.g. _closes #issue-number_

2020-10-07 09:38 UTC, Samweli commented
@ricardogsilva I think this PR is ready to be merged.

2020-10-07 12:08 UTC, merged